version: '3.8'  
services:  
  postgres_local:  
    image: postgres:15  
    container_name: gomoku_postgres_local  
    environment:  
      POSTGRES_USER: gomoku_user  
      POSTGRES_PASSWORD: gomoku_password  
      POSTGRES_DB: gomoku_db  
    ports:  
      - "5435:5432" # 左侧为宿主机端口，右侧为容器内端口
  redis_local:  
    image: redis:7-alpine  
    container_name: gomoku_redis_local  
    ports:  
      - "6385:6379"  
